<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>AudioFlow.Core</RootNamespace>
    <AssemblyName>AudioFlow.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AudioFlow.Models\AudioFlow.Models.csproj" />
  </ItemGroup>

</Project>
