<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>AudioFlow.ConsoleApp</RootNamespace>
    <AssemblyName>audioflow</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AudioFlow.Core\AudioFlow.Core.csproj" />
    <ProjectReference Include="..\AudioFlow.Models\AudioFlow.Models.csproj" />
    <ProjectReference Include="..\AudioFlow.Rules\AudioFlow.Rules.csproj" />
    <ProjectReference Include="..\AudioFlow.ProcessLoopback\AudioFlow.ProcessLoopback.csproj" />
  </ItemGroup>

</Project>
